Implement convert HTML to ReactJS Typescript
st-longngo/FE-React-Ngo-Dac-Quoc-Long-ST0057 pull request #1
Opened 2022-06-30 10:21 UTC by st-longngo

#### References
- [Task/Bug URL](https://www.figma.com/file/CUQiZbPKOlfjHZn9hBqrPh/Fashion?node-id=0%3A1)
#### Description
- Implement convert HTML to ReactJS Typescript
#### Screenshots
![screencapture-localhost-3001-2022-06-30-17_20_15](https://user-images.githubusercontent.com/106951904/176654185-74268775-4809-4eda-a848-677d9c96e0bc.png)
#### Checklist
- [x] Code đã được build và test ở môi trường local.
- [x] Tất cả những lỗi cơ bản đã được tìm thấy và sửa chữa

2022-06-30 11:19 UTC, st-trangnguyen requested changes
Hi Long,
Em chỉnh lại folder chị sẽ review tiếp nhé.
- tên folder phải là kebab-case
- những cái dùng chung ở folders `components` của em hiện tại. những cái Badge, Button em tạo folder tên là `partials` và chuyển hết vào đó nhé. trong components dùng chung toàn app mình sẽ chia ra nhiều loại như `partials`, `layout`, `common`...
- tiếp theo trong `home`, em cũng tạo 1 folder `partials` và chuyển hết những file/folder của các sections vào đó nhé
- phần selected product và today product nếu đúng thì chỉ là 1 component rồi hì

2022-06-30 15:05 UTC, st-trangnguyen requested changes

2022-06-30 15:05 UTC, st-trangnguyen commented on src/app/components/PolicyItem.tsx
> +    <li className='policy-item'>
Rank A: Sử dụng double quote trong renderer như html bình thường e nhé. check tất cả nha

2022-06-30 15:05 UTC, st-trangnguyen commented on src/app/components/ProductItem.tsx
> +import React from 'react';
mấy component này cũng là 1 partial bình thường nha em

2022-06-30 15:05 UTC, st-trangnguyen commented on src/app/components/partials/Button.tsx
> +  name: string,
Rank C: should be `title`, not name

2022-06-30 15:05 UTC, st-trangnguyen commented on src/app/components/partials/Button.tsx
> +    <a href='' className={type && typeSection ? `btn btn-${type} btn-${typeSection}` : (!typeSection ? `btn btn-${type}` : `btn`)}>
Rank B: đoạn code dài quá, bỏ trong renderer khó nhìn, sau này nhỡ nó dài ra nữa thì khó maintance , em tạo function cho việc render class. review function đó dễ hơn, c đọc rúi quá

2022-06-30 15:05 UTC, st-trangnguyen commented on src/app/components/partials/Button.tsx
> +export default Button
Rank C: Thiếu `;` nhiều quá.  Check kĩ lại hoặc research config thêm eslint đi em

2022-06-30 15:05 UTC, st-trangnguyen commented on src/app/pages/Home/Home.tsx
> +        <ProductList title='Selected just for you' button={true} />
Rank B: đọc bài viết này đoán xem chị comment gì nhoa :)))
https://betterprogramming.pub/8-ways-to-write-clean-react-code-610c502ccf39

Rank C: nếu props true/false hay gì đó thì em đặt tên như này có nghĩa hơn nè `hasButton`

2022-06-30 15:05 UTC, st-trangnguyen commented on src/app/pages/Home/partials/about/About.tsx
> +    button: {
Rank C: Cái đống button này là từ bài css em đã làm sai rồi nên nó mới cực với thấy rúi nhùi như ri đây, sau khi hoàn thành xong các comment khác thì nói chị chỉ lại chỗ này

2022-06-30 15:05 UTC, st-trangnguyen commented on src/app/pages/Home/partials/product-list/ProductList.tsx
> +        {button ? (
Rank C: cái ni cũng sai từ cái html luôn. nên luôn luôn có 1 cái div và 1 thẻ heading, mình chỉ cần if else ở cái thẻ button thôi

2022-06-30 15:05 UTC, st-trangnguyen commented on src/app/pages/Home/partials/product-list/ProductList.tsx
> +const PRODUCTS = [
Rank C: cái ni là list data có thể thay đổi (push/delete item) nên tên cứ đặt camelCase bình thường em nhé

2022-06-30 15:05 UTC, st-trangnguyen commented on src/app/pages/Home/partials/product-list/ProductList.tsx
> +                  name={product.name}
Rank B: Truyền vô trớt luôn cái `product`, vào bên kia em muốn lấy field gì thì lấy ra. dùng props truyền tầm gần 70% nội dung của object thì truyền vào hết đc rùi đó

2022-06-30 15:05 UTC, st-trangnguyen commented on src/app/pages/Home/partials/product-list/ProductList.tsx
> +import React from 'react';
Rank C: Nếu component list nằm ở bên này thì chị ko nghĩ product item lại nằm ở shared. 2 cái này thường sẽ phải đi chung với nhau

2022-06-30 15:05 UTC, st-trangnguyen commented on src/app/pages/Home/partials/product-list/ProductList.tsx
> +const ProductList: React.FC<IProductListProps> = ({ title, button }) => {
Rank A: ProductList nhưng ko có nhận props `product list` là ko có ổn nha, tùy từng section mà render là list của từng cái chứ, mặc dù UI họ vẽ giống nhau nhưng thực tế selected product vs today product sẽ là data lưu riêng biệt, chứ ko họ tách 2 section làm gì

2022-06-30 15:38 UTC, st-trangnguyen requested changes
<img width="292" alt="image" src="https://user-images.githubusercontent.com/63229420/176718222-9286b7bf-5fe5-4fd4-9f5e-73169f99d521.png">

app => toàn bộ liên quan components, Ui, ...
assets => chứa ảnh ọt, icon....
stylesheets => bik rùi

như trên mới đúng nhé, như như em gì cũng nằm trong app nhưng 2 file của App lại ko nằm trong app, tội nghiệp chúng nó :)))

2022-06-30 15:48 UTC, st-longngo commented on src/app/pages/Home/partials/about/About.tsx
> +    button: {
Dạ chị

2022-06-30 15:48 UTC, st-longngo commented on src/app/pages/Home/Home.tsx
> +        <ProductList title='Selected just for you' button={true} />
Link này không đọc được chị ơi

2022-06-30 15:49 UTC, st-longngo commented on src/app/pages/Home/partials/about/About.tsx
> +    button: {
Chỗ button với badge em cũng loạn luôn

2022-06-30 15:53 UTC, st-trangnguyen commented on src/app/pages/Home/Home.tsx
> +        <ProductList title='Selected just for you' button={true} />
<img width="399" alt="image" src="https://user-images.githubusercontent.com/63229420/176722827-310474fc-6730-450f-979e-f0897217dc7f.png">

2022-06-30 15:55 UTC, st-trangnguyen commented on src/app/pages/Home/Home.tsx
> +        <ProductList title='Selected just for you' button={true} />
chị chụp cho chỗ chị muốn nói rùi đó, nhưng cài WARP đi là đọc được. nhiều cái hay lắm
https://1.1.1.1/

2022-06-30 17:12 UTC, st-vantran commented on src/app/components/PolicyItem.tsx
> +    <li className='policy-item'>
Này lỗi của anh. Hồi chiều a hiểu sai câu hỏi nên nói đổi hết đó em. Sorry!

2022-06-30 23:08 UTC, st-longngo commented on src/app/pages/Home/Home.tsx
> +        <ProductList title='Selected just for you' button={true} />
Dạ chị

2022-07-01 03:25 UTC, st-trangnguyen requested changes

2022-07-01 03:25 UTC, st-trangnguyen commented on src/app/pages/Home/partials/SectionAbout.tsx
> +interface IAboutItem {
Rank B: Cái ni giống bên chỗ item ri hè? Nếu nhiều file cần dùng interface ni thì em đưa vào trong `shared/types`

2022-07-01 03:25 UTC, st-trangnguyen commented on src/app/pages/Home/partials/SectionAbout.tsx
> +const dataAbout: IAboutItem[] = [
Rank C: Nãy chị ko hiểu ý câu hỏi, cái này đưa vào trong component List để khỏi cần truyền prod đc em nhé, nó vốn là data của thằng List nên mình đưa vào trong đó

Check lại tương tự những chỗ khác nha

2022-07-01 03:25 UTC, st-trangnguyen commented on src/app/shared/components/partials/Button.tsx
> +    <button className={customClass ? `btn ${customClass}`: 'btn'}>
Rank B: ko cần if else ở những chỗ này em, `customClass` rỗng thì nó rỗng thôi, chứ ko cần phải if else để in ra mỗi `btn`

2022-07-01 03:25 UTC, st-trangnguyen commented on src/app/shared/components/partials/Link.tsx
> +interface ILinkProps {
Rank C: link nào cũng là href giống nhau?

2022-07-01 03:25 UTC, st-trangnguyen commented on src/app/shared/interfaces/product.tsx
> +export interface IProduct {
Rank A: interface mà đuôi là tsx ??? 🔪

2022-07-01 03:25 UTC, st-trangnguyen commented on src/App.tsx
>  import React from 'react';
App thì đưa vào trong folder `app`

2022-07-01 03:25 UTC, st-trangnguyen commented on src/App.css
> -.App {
ko dùng file này xóa luôn

2022-07-01 06:51 UTC, st-trangnguyen approved these changes
Còn nhiều cái cần cải thiện hơn chị, chị sẽ chỉ tiếp trong những bài tập sau nhé. Bài này chị tạm approve để tiếp tục

2022-07-01 06:53 UTC, merged