Implement Perform Cart for Eshop Page
st-longngo/FE-React-Ngo-Dac-Quoc-Long-ST0057 pull request #2
Opened 2022-07-01 09:23 UTC by st-longngo

#### References
- [Task/Bug URL](https://www.figma.com/file/CUQiZbPKOlfjHZn9hBqrPh/Fashion?node-id=8%3A194)
#### Description
- Implement Perform Cart for Eshop Page
#### Screenshots
![screencapture-localhost-3001-2022-07-01-16_21_35](https://user-images.githubusercontent.com/106951904/176866371-2167c2e4-c7d2-4a83-b923-1a50b70d2ad2.png)
#### Checklist
- [x] Code đã được build và test ở môi trường local.
- [x] Tất cả những lỗi cơ bản đã được tìm thấy và sửa chữa.

2022-07-02 10:04 UTC, st-vantran commented on src/app/App.tsx
> +import { getData, setData } from './shared/common/common';
Em sắp xếp lại thứ tự import nhé.
Anh thường sx như sau:
```
1. import từ thư viện
2. import component
3. import functions, constant
```

2022-07-02 10:04 UTC, st-vantran commented on src/app/pages/Cart/Cart.tsx
> +export default Cart
Add new line.
Em check những file còn lại luôn nhé

2022-07-02 10:04 UTC, st-vantran commented on src/app/pages/Cart/partials/CartItem.tsx
> +        if (cart[cartIndex].quantity - 1 > 0) {
Sao không để > 1 luôn em?

2022-07-02 10:04 UTC, st-vantran commented on src/app/pages/Cart/partials/CartItem.tsx
> +        <button
Em có tạo Component Button rồi mà

2022-07-02 10:04 UTC, st-vantran commented on src/app/pages/Cart/partials/CartItem.tsx
> +        onClick={() => deleteProductInCart()}
Nếu em không cần truyền params nào vào fn thì nên để thẳng
```ts 
onClick={deleteProductInCart}
```
Vì nếu em để trong 1 callback thì mỗi lần render nó sẽ sinh ra 1 function mới nữa. (nghĩa là xử lý delete mà trong bộ nhớ có 2 functions luôn --> dư) 
Sau này mình kết hợp với useCallback để hạn chế việc sinh ra những fn mới này

2022-07-02 10:04 UTC, st-vantran commented on src/app/pages/Cart/partials/CartList.tsx
> +      <li className="cart-row">
Đưa thằng `<li>` này ra ngoài ul em nhé hoặc đổi thẻ, nó là title mà có format giống như cart-item đâu. Ai đời trong `<ul>` mà có 2 kiểu format `<li>` khác nhau vậy đâu

2022-07-02 10:04 UTC, st-vantran commented on src/app/pages/Home/partials/SectionSelected.tsx
>  import Image from '../../../../assets/images';
Em xem thằng `<SectionSelected>` với `<SectionToday>` chỉ khác nhau thằng title với productlist thôi.
Nên để vào chung 1 component nhé em, rồi truyền props title với productlist vào thôi.

2022-07-02 12:12 UTC, st-longngo commented on src/app/pages/Home/partials/SectionSelected.tsx
>  import Image from '../../../../assets/images';
Dạ anh

2022-07-04 01:07 UTC, st-vantran approved these changes

2022-07-04 01:46 UTC, st-trangnguyen requested changes

2022-07-04 01:46 UTC, st-trangnguyen commented on src/app/App.tsx
> +  useEffect(() => {
Rank B: Dùng hàm set storage em đã define, format code đẹp lại, thêm cách ở sau mấy dấu `,`, thêm `;` vào

2022-07-04 01:46 UTC, st-trangnguyen commented on src/app/pages/Home/Home.tsx
> +      <SectionProduct productList={productList} title='Selected just for you' hasButton={true} />
Rank C: 
- `hasButton={true}` => chị đã comment 1 lần rồi
- title='Selected just for you' => nháy đôi

2022-07-04 01:46 UTC, st-trangnguyen commented on src/app/pages/Home/partials/ProductItem.tsx
> +import { ICart } from "./../../../shared/interfaces/cart";
Rank B: Thực chất ở cart cũng chỉ là 1 product trong giỏ hàng, nên tạo interface tách product với cart ra là sai hoàn toàn nghen

2022-07-04 01:46 UTC, st-trangnguyen commented on src/app/pages/Home/partials/ProductItem.tsx
> +const ProductDiscount = ({ price, discount }: IProductDiscountProps) =>
Rank B: Không tạo component trong component nha em, tách file ra

2022-07-04 01:46 UTC, st-trangnguyen commented on src/app/shared/components/partials/SectionTitle.tsx
> +      {hasButton && <Button title="show more" customClass='btn btn-border'/>}
Rank C: Mấy cái props string em nhớ dùng "" hết

2022-07-04 01:46 UTC, st-trangnguyen commented on src/app/App.tsx
> +import Header from "./shared/components/layout/Header";
Rank C: Làm gọn code những chỗ export từ cùng 1 folder ra đi em. Tạo file index.ts như hôm bữa c nói

2022-07-04 08:20 UTC, merged