Implement Perform Redux for Shopping Cart
st-longngo/FE-React-Ngo-Dac-Quoc-Long-ST0057 pull request #4
Opened 2022-07-05 09:03 UTC by st-longngo

#### References
- [Task/Bug URL](https://www.figma.com/file/CUQiZbPKOlfjHZn9hBqrPh/Fashion?node-id=0%3A1)
#### Description
- Implement Perfom Redux for Shopping Cart
#### Screenshots
- Home
![screencapture-localhost-3001-2022-07-05-15_59_58](https://user-images.githubusercontent.com/106951904/177291775-a457eba7-b5cf-44b8-a548-04ac2b4a8876.png)
- Cart
![screencapture-localhost-3001-cart-2022-07-05-16_02_41](https://user-images.githubusercontent.com/106951904/177291894-c163be16-0028-4aeb-b470-c5d78ba6904e.png)

#### Checklist
 - [x] Run correctly as the requirement.
 - [x] The code has been built and tested in the local environment.

2022-07-05 12:43 UTC, st-trangnguyen requested changes

2022-07-05 12:43 UTC, st-trangnguyen commented on src/app/pages/Cart/cart.actions.ts
> +export const increseQuantityCart = (cart: ICart) => {
Rank B: Thay vì em phải define 2 actions, thì em có thể viết gom 1 action nhận param ngoài cart ra thì thêm 1 cái là value tăng giảm bao nhiêu nữa nha nữa nha

2022-07-05 12:43 UTC, st-trangnguyen commented on src/app/pages/Cart/cart.reducer.ts
> +import { IActionReducer, IStateReducer } from '../../shared/interfaces/reducer';
Rank C: IActionReducer => em search thêm dùng redux với typescript thì redux nó có export 1 số type cho mình dùng khỏi cần define riêng nha

Rank B: `IStateReducer` => `IRootState` . state reducer là gì

2022-07-05 12:43 UTC, st-trangnguyen commented on src/app/pages/Cart/cart.reducer.ts
> +        const newCart = state.cart.filter(
Rank A: ko có dùng filter chỉ để remove 1 thằng nha, dùng built in function của js cho đúng mục đích của nó hỉ

2022-07-05 12:43 UTC, st-trangnguyen commented on src/app/pages/Cart/partials/SectionCart.tsx
> +  const { cart } = useSelector((state: any) => state.cartReducer);
Rank B: `state: any` => tìm type mà redux có export cho mình dùng thay vì dùng any nha

2022-07-05 12:43 UTC, st-trangnguyen commented on src/app/pages/Home/Home.tsx
> +      setProductList(respone.data);
Rank B: nếu response bị null thì sao, đừng tin api quá, fe mình nên phủ đầu mọi trường hợp

2022-07-05 12:43 UTC, st-trangnguyen commented on src/app/pages/Home/partials/ProductItem.tsx
> +import { useDispatch } from "react-redux";
Rank B: Sau mà làm bài xong ko tự review để sai mấy lỗi convention ni thì coi chừng hỉ

2022-07-05 12:43 UTC, st-trangnguyen commented on src/app/redux/appReducer.ts
> +  cartReducer: cartReducer
Rank B: state key đặt hay hay xí em `cart: cartReducer`

2022-07-05 12:43 UTC, st-trangnguyen commented on src/app/shared/components/layout/Header.tsx
>    const cartNumber = cart.reduce((acc: number, item: ICart) => acc + item.quantity, 0);
Dùng useEffect watch cart thay đổi, ko có tạo biến const bt như zậy. chỉ update khi cần thiết thôi

2022-07-05 12:43 UTC, st-trangnguyen commented on src/app/redux/appReducer.ts
> +import React from 'react';
Rank B: file này là app.reducers.ts đúng ko em. Vậy em để ở trong folder app thôi là đc rồi

2022-07-05 12:46 UTC, st-trangnguyen requested changes

2022-07-05 12:46 UTC, st-trangnguyen commented on src/app/shared/types/types.ts
> +export const ADD_CART = 'ADD_CART';
Rank B: Cái này là em đang define constant string, em move file này vào folder `constants` còn folder `types` này đúng phải là của type/interface

2022-07-05 15:49 UTC, st-longngo commented on src/app/redux/appReducer.ts
> +import React from 'react';
Cái này là store của app á chị. Chiều anh Văn bảo để ở đó á chị.

2022-07-05 16:06 UTC, st-vantran commented on src/app/pages/Home/Home.tsx
> +        setLoading(true);
Biến loading của em bị ngược nhé. loading false mà show loading à .
Với lại em setLoading ở trong thằng if thì nó xoay mãi nếu thằng response trả về rỗng.
Lôi ra ngoài đi em

2022-07-06 01:15 UTC, st-longngo commented on src/app/shared/components/layout/Header.tsx
>    const cartNumber = cart.reduce((acc: number, item: ICart) => acc + item.quantity, 0);
Cart ở header update khi cart thay đổi luôn á chị

2022-07-06 01:19 UTC, st-trangnguyen commented on src/app/shared/components/layout/Header.tsx
>    const cartNumber = cart.reduce((acc: number, item: ICart) => acc + item.quantity, 0);
Thì có phải là mình watch cart thay đổi rồi update cart number ko?

2022-07-06 01:23 UTC, st-trangnguyen commented on src/app/redux/appReducer.ts
> +import React from 'react';
store là cái gì em? chị thấy em đặt tên file là app reducer mà? vậy đây là file để combine hết reducer vào chứ, đúng không?
- thứ nhất, đã tách file liên quan đến redux như actions, reducers cho từng thằng rồi. thì ko có folder của redux nào được tồn tại hết. chỉ nên chọn 1 trong 2 cách tách riêng hoặc tạo folder store của redux, mà mình đã chọn tách riêng thì tách riêng
- thứ 2. những file khác đã đặt tên là xxx.reducers.ts mà file này thì đặt là appReducer? 1 cái source code mà tùm lum kiểu đặt tên. nó kó có đẹp

Đây là 1 boilerplate về cấu trúc thư mục trong dự án react. em có thể dành thời gian xem qua để biết thêm nhiều kiến thức.
https://github.com/st-trangnguyen/b-react-ts/tree/main/src/app

2022-07-06 02:00 UTC, st-longngo commented on src/app/redux/appReducer.ts
> +import React from 'react';
Dạ chị

2022-07-06 02:22 UTC, st-trangnguyen requested changes

2022-07-06 02:22 UTC, st-trangnguyen commented on src/app/pages/Cart/cart.reducers.ts
> +          setData('cart', [...state.cart]);
```
          setData('cart', [...state.cart]);
          return {
            ...state,
            cart: [...state.cart],
          };
```
Rank B: Khi thấy code bị duplicate thì mình phải làm chi hè

2022-07-06 02:22 UTC, st-trangnguyen commented on src/app/pages/Home/Home.tsx
> +        setLoading(true);
Rank B: Rứa get data bị lỗi em cho nó show loading miết luôn ờ @@

2022-07-06 09:49 UTC, st-vantran approved these changes

2022-07-06 09:49 UTC, st-vantran commented on package.json
> +    "redux-logger": "^3.0.6",
xoá thằng này nhé em, dùng ở dưới dev rồi

2022-07-06 09:49 UTC, st-vantran commented on src/app/pages/Cart/cart.reducers.ts
> +      if(action.payload.increase) {
If else if else gì loạn vậy em. Xong mỗi condition `return` luôn. Tạo hàm xử lý thằng value return.

2022-07-06 09:49 UTC, st-vantran commented on src/app/pages/Cart/cart.reducers.ts
> +      setData('cart', [...state.cart]);
Check cart thay đổi rồi setData cart 1 lần luôn em. Dùng useEffect với dependency = cart lấy từ store

2022-07-06 10:38 UTC, st-trangnguyen requested changes

2022-07-06 10:38 UTC, st-trangnguyen commented on src/app/pages/Home/home.reducers.ts
> +const initialStateHome = {
Rank C: chị có 1 case như sau. trang home này ngoài products ra mình cần get data thêm của những cái như collection chẳng hạn. thì `isLoading` mà `error` em quản lí như phía dưới nó có còn hợp lí ko?

2022-07-06 14:45 UTC, st-longngo commented on src/app/pages/Cart/cart.reducers.ts
> +      if(action.payload.increase) {
Cái này mà tạo function thì return của return á anh

2022-07-06 15:49 UTC, st-longngo commented on src/app/pages/Home/home.reducers.ts
> +const initialStateHome = {
Em nghĩ là isLoading với error em sẽ là dùng chung cho tất cả get data luôn á chị. Nếu get data collection success hay error thì set lại 2 cái này thôi.

2022-07-07 06:45 UTC, st-trangnguyen approved these changes

2022-07-07 06:45 UTC, merged