Implement Redux-saga Get API Product and Categories
st-longngo/FE-React-Ngo-Dac-Quoc-Long-ST0057 pull request #6
Opened 2022-07-07 07:59 UTC by st-longngo

#### Description
- Implement Redux-saga Get API Product and Categories
#### Screenshots
![screencapture-localhost-3000-2022-07-07-14_58_20](https://user-images.githubusercontent.com/106951904/177722440-2e5637a3-2ce3-41b6-a3bc-c64e97b98d0c.png)

#### Checklist
-[x] Run correctly as the requirement.
-[x]The code has been built and tested in the local environment.

2022-07-07 08:46 UTC, st-vantran commented on src/app/pages/Home/home.actions.ts
> +export const getProductsSuccess = (posts: any) => ({
Xem tên lại nghen em

2022-07-07 08:46 UTC, st-vantran commented on src/app/pages/Home/home.middlewares.ts
> +const ENDPOINT = 'https://6088e20da6f4a300174271e7.mockapi.io';
Tạo folder config, file endpoint để baseURL vào đó nhé em

2022-07-07 08:46 UTC, st-vantran commented on src/app/pages/Home/partials/ProductItem.tsx
> +        {(!isLoading && !isLoadingProduct) && <p className='product-category'>{renderCategory()}</p>}
Tại sao lại check Loading ở đây nhỉ? Em phải chặn từ lúc list ra product luôn chớ

2022-07-07 08:46 UTC, st-vantran commented on src/app/pages/Home/Home.tsx
> +  const isLoadingCategory = useSelector((state: RootState) => state.categories.isLoading);
Define ra rồi không dùng hả em?

2022-07-07 09:33 UTC, st-vantran commented on src/app/pages/Home/home.reducers.ts
> +        categories: action.payload,
Anh có 1 option khác ở đây, lưu categories ở dạng Object. Khi sử dụng chỉ cần dùng `categories[category_id]` là được. Tránh chạy mỗi vòng lặp khi render thằng item
```ts
 case TYPES.GET_CATEGORIES_SUCCESS:
      return {
        ...state,
        categories: Object.fromEntries(
          [...action.payload].map((item) => Object.values(item))
        ),
        isLoading: false,
        error: '',
      };
```

```ts
categories: 
{1: "JUMPSUITS"
2: "SHIRT"
3: "TROUSER"
4: "JEANS"}

categories['2'] = "SHIRT"
```

2022-07-07 10:51 UTC, st-vantran commented on src/app/pages/Home/home.middlewares.ts
> +    yield put(getProductsSuccess(res.data));
Anh có 1 option khác ở đây, lưu categories ở dạng Object. Khi sử dụng chỉ cần dùng `categories[category_id]` là được. Tránh chạy mỗi vòng lặp khi render thằng item
```ts
const categories = Object.fromEntries(
          [...res.data].map((item) => Object.values(item))
        )
 yield put(getProductsSuccess(categories));
```

```ts
categories: 
{1: "JUMPSUITS"
2: "SHIRT"
3: "TROUSER"
4: "JEANS"}

categories[2] = "SHIRT"
```

2022-07-08 02:36 UTC, st-trangnguyen requested changes

2022-07-08 02:36 UTC, st-trangnguyen commented on src/app/app.reducers.ts
> +import { homeReducer, homeCategoriesReducer} from './pages/home/home.reducers';
Rank B: Đặt tên mấy cái reducer này khó hiểu quá, có thể đặt là productReducer, categoryReducer

Sau này em đi đâu dùng cũng được, chứ em đặt là home mà đi những trang ko phải là home dùng cũng kì

2022-07-08 02:36 UTC, st-trangnguyen commented on src/app/pages/Home/home.reducers.ts
> +interface IStateProductsHome {
Rank B: Cứ mắc cái chữ "Home" vô làm chi em hè, nó sẽ làm code em cảm giác bị giới hạn ko mở rộng ra đc khỏi home

Rank A: Tât cả những state đề có chung 1 kiểu đó là có 1 data, 1 isLoading, 1 error, em tạo state để dùng chung đc, ko tách ra từng cái như vậy

2022-07-08 03:12 UTC, st-vantran approved these changes

2022-07-08 03:12 UTC, st-vantran commented on src/app/pages/Home/home.reducers.ts
> +        data: Object.fromEntries(action.payload.map((item: any) => Object.values(item))),
Xử lý logic bên middleware nhé em

2022-07-08 04:17 UTC, merged